### ISSUE TITLE
Questions about Results

### ISSUE THREAD

**Issue by zzysay** [MurtuzaBohra/SimpDOM#1]
Thanks to the open source code, SimpDOM is a very interesting work！

However, when I use the checkpoint provided by the author to reproduce the (test) results, there seems to be some accidents, the Rec is `nan` for all attributes ...

![image](https://user-images.githubusercontent.com/22562350/142145843-79560ce1-fe0e-4289-a294-29704ba18d4f.png)

Here, I copy all the contents of `test.ipynb` into the `test py` file and run it directly.

**Comment by MichaelAzmy** [comment]
I have the same issue, have you solved that?

**Comment by MurtuzaBohra** [comment]
There was an issue in the data. Labels were missing in the data, thus the metrics calculation was resulting "nan". Please use this updated link to download data and weights https://drive.google.com/file/d/1aMuHb8RT_GrKr6VoUvmDsObEwIqypkHy/view?usp=sharing. I have verified, this should work fine now. Also updated the link in the README file.

@zzysay @MichaelAzmy Thanks for point this out.
