### ISSUE TITLE
Training a model

### ISSUE THREAD

**Issue by MichaelAzmy** [MurtuzaBohra/SimpDOM#2]
First, I want to thank you for putting effort to implement the paper.
The code is clean but I have some hard time understanding the steps needed to preprocess data for training any new vertical and possibly new datasets.

I can see multiple scripts under DatasetCreation but I can't understand the steps nor the dependencies.
Is there a single entry point for preprocessing the data?
Can you point me to the steps?

Thanks.

**Comment by MurtuzaBohra** [comment]
The "train.ipynb" notebook contains the steps to process the new verticals. You need to unzip the SWDE data set in the "data" folder and give that path to "datapath" variable and give the vertical name of your choice. Example of the directory structure is shows in the below image.

<img width="1010" alt="directory_structure" src="https://user-images.githubusercontent.com/10773966/144736390-eda4eecb-a3d5-471c-b636-ac68781f327c.png">
